name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        jdk: [8, 11, 17]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: liberica
          cache: maven
      - name: Build
        run: mvn -V compile
      - name: Test
        run: mvn verify
      - name: Package
        run: mvn package